version: '3.8'

services:
  payment-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_URL=jdbc:mysql://host.docker.internal:3306/devops_platform_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=1111
      - TOSS_PAYMENTS_CLIENT_KEY=${TOSS_PAYMENTS_CLIENT_KEY}
      - TOSS_PAYMENTS_SECRET_KEY=${TOSS_PAYMENTS_SECRET_KEY}
      - TOSS_PAYMENTS_SECURITY_KEY=${TOSS_PAYMENTS_SECURITY_KEY}
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092
      - EUREKA_DEFAULT_ZONE=http://host.docker.internal:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"