apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: payment-service
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  DB_USERNAME: cGF5bWVudF91c2Vy  # payment_user
  DB_PASSWORD: cGF5bWVudF9wYXNz  # payment_pass
  STRIPE_API_KEY: c2tfdGVzdF9jaGFuZ2VfbWU=  # sk_test_change_me
  STRIPE_WEBHOOK_SECRET: d2hzZWNfY2hhbmdlX21l  # whsec_change_me