replicaCount: 3

image:
  repository: your-docker-registry.com/be-payment-service
  tag: "prod-latest"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "1000"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
  hosts:
    - host: api.yourcompany.com
      paths:
        - path: /payment
          pathType: Prefix
  tls:
    - secretName: payment-service-prod-tls
      hosts:
        - api.yourcompany.com

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  SPRING_PROFILES_ACTIVE: production

secrets:
  DB_USERNAME: prod_payment_user
  DB_PASSWORD: prod_payment_secure_pass
  TOSS_PAYMENTS_CLIENT_KEY: YOUR_PRODUCTION_CLIENT_KEY
  TOSS_PAYMENTS_SECRET_KEY: YOUR_PRODUCTION_SECRET_KEY
  DB_URL: jdbc:postgresql://postgresql-prod:5432/payment_db_prod
  KAFKA_BOOTSTRAP_SERVERS: kafka-prod:9092
  EUREKA_DEFAULT_ZONE: http://eureka-prod:8761/eureka/