apiVersion: v2
name: payment-service
description: A Helm chart for Payment Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - payment
  - microservice
  - spring-boot
home: https://github.com/your-org/BE-PaymentService
sources:
  - https://github.com/your-org/BE-PaymentService
maintainers:
  - name: Payment Service Team
    email: payment-team@yourcompany.com